
name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          echo "===== ROOT FILES ====="
          ls -la
          echo "===== SEARCH pubspec.yaml ====="
          find . -name pubspec.yaml

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Find project path
        id: find_project
        run: |
          PROJECT_PATH=$(dirname $(find . -name pubspec.yaml | head -n 1))
          echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
          echo "Project found at: $PROJECT_PATH"

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Build APK
        run: flutter build apk --release --dart-define=FIREBASE_DATABASE_URL=https://tradelens-academy-default-rtdb.firebaseio.com
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_PATH }}/build/app/outputs/flutter-apk/app-release.apk
